name: sending-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client 
  - black
  - click
  - conda-build
  - ipython
  - pytest
  - python=3.8
  - python-dotenv
  - pysftp
  - requests
  - vcrpy
