package:
  name: sending
  version: 0.0.1

source:
  git_rev: v0.0.1
  git_url: https://github.com/ehatton/sending.git

requirements:
  build:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - click
    - colorama # [win]
    - pysftp
    - requests

build:
  noarch: python
  entry_points:
    - sending = sending.cli:cli
  script: python -m pip install --no-deps --force-reinstall . 

test:
  commands:
    - sending --help
  imports:
    - sending

about:
  home: https://github.com/ehatton/sending
  license: MIT
  license_file: LICENSE
